server:
  port: 5000
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/backend-db
    username: postgres
    password: fatballs123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
token:
  signing:
    key: tHw9ZBiaoYow1cdrEOsUeubdqbpiY/hX0XseMCa3O/qbZJYKKGMXoV/Enwx0BHDS7C9KGYMCd99QfGL/vtorxQ==
